//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYS.IO.Socket.WinFormClient.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.4.140")]
        public string SYS_ServerIP
        {
            get
            {
                return ((string)(this["SYS_ServerIP"]));
            }
            set
            {
                this["SYS_ServerIP"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int SYS_ServerPort
        {
            get
            {
                return ((int)(this["SYS_ServerPort"]));
            }
            set
            {
                this["SYS_ServerPort"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PDA001")]
        public string SYS_PID
        {
            get
            {
                return ((string)(this["SYS_PID"]));
            }
            set
            {
                this["SYS_PID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\CYS\\SocketDebug\\Client\\UpLoad\\")]
        public string SYS_UpLoadPath
        {
            get
            {
                return ((string)(this["SYS_UpLoadPath"]));
            }
            set
            {
                this["SYS_UpLoadPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\CYS\\SocketDebug\\Client\\DownLoad\\")]
        public string SYS_DownLoadPath
        {
            get
            {
                return ((string)(this["SYS_DownLoadPath"]));
            }
            set
            {
                this["SYS_DownLoadPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Git-1.9.4-preview20140611.exe")]
        public string SYS_UpLoadFName
        {
            get
            {
                return ((string)(this["SYS_UpLoadFName"]));
            }
            set
            {
                this["SYS_UpLoadFName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SYS_DownLoadFName
        {
            get
            {
                return ((string)(this["SYS_DownLoadFName"]));
            }
            set
            {
                this["SYS_DownLoadFName"] = value;
            }
        }
    }
}
